language: python
dist: xenial
sudo: false
addons:
  postgresql: "9.6"

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_USER=postgres
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_ENCRYPT_KEY=tests

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - pip install psycopg2 sqlalchemy
  - pip install -U flake8 coverage pytest pytest-cov
  - pip install coveralls
  - pip install .

script:
  - flake8 anyblok_delivery
  - psql -c 'create database travis_ci_test;' -U postgres
  - anyblok_updatedb --install-bloks delivery delivery_colissimo
  - py.test --cov-report= --cov=anyblok_delivery  anyblok_delivery/bloks/
  
after_success:
  coveralls --data_file=.coverage --config_file=.coveragerc
