language: python
sudo: false
addons:
  postgresql: "9.6"

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install psycopg2 sqlalchemy
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install WebTest
  - pip install coveralls
  - pip install .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres
    - ANYBLOK_ENCRYPT_KEY=tests

script:
  - flake8 anyblok_delivery
  - anyblok_createdb --install-bloks delivery colissimo
  - nosetests anyblok_delivery/bloks/ --with-anyblok-bloks -v -s --with-coverage --cover-package=anyblok_delivery
  
after_success:
  coveralls
