language: python
dist: xenial
sudo: false
addons:
  postgresql: "9.6"

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_USER=postgres
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_ENCRYPT_KEY=tests

matrix:
    include:
      - python: "pypy3.5"
        env: ANYBLOK_DATABASE_DRIVER=postgresql+psycopg2cffi
    allow_failures:
      - python: "pypy3.5"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3.5' ]]; then pip install psycopg2cffi; else pip install psycopg2; fi
  - pip install sqlalchemy
  - pip install -U flake8 coverage pytest pytest-cov
  - pip install coveralls
  - pip install .

script:
  - flake8 anyblok_delivery
  - anyblok_createdb --install-bloks delivery delivery_colissimo
  - py.test --cov-report= --cov=anyblok_delivery  anyblok_delivery/bloks/
  
after_success:
  coveralls
